### ISSUE TITLE
can you add Pangolin ?

### ISSUE THREAD

**Issue by 0iui0** [leleliu008/ndk-pkg-formula-repository#7]
would you add the formula for https://github.com/stevenlovegrove/Pangolin, or if there is a  way to add my own formula ?

**Comment by leleliu008** [comment]
you can run `ndk-pkg formula create pangolin` command to create `pangolin` package's formula file, this command will invoked `EDITOR` environemt. if this envionent variable is not set, ndk-pkg will search vim, if found, ndk-pkg will use it.

![Screenshot from 2022-07-26 14-41-04](https://user-images.githubusercontent.com/3040852/180940462-23961454-9200-4d5e-81bd-3f1508ccd562.png)

I will try to add this package to this repo.
I will notice you after adding.

**Comment by leleliu008** [comment]
I notice that https://github.com/stevenlovegrove/Pangolin/issues/542 say Pangolin is now not support for Android, do you known Pangolin can really be built for Android?

**Comment by 0iui0** [comment]
> 

I'll  try, thx.

**Comment by 0iui0** [comment]
> I notice that [stevenlovegrove/Pangolin#542](https://github.com/stevenlovegrove/Pangolin/issues/542) say Pangolin is now not support for Android, do you known Pangolin can really be built for Android?

I have not try it yet, but it seems someone  have already make it work.
https://github.com/FangGet/pangolin_android.git

**Comment by leleliu008** [comment]
6 yeas ago, too old, It's not for latest version.
